apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: loandefault
spec:
  default:
    predictor:
      minReplicas: 1
      sklearn:
        storageUri: "gs://cm_mav_bucket1/loan_default"